### ISSUE TITLE
An unexpected error occurred when executing the action on the 'basic12sp4' machine. Please report this as a bug:

### ISSUE THREAD

**Issue by rmontes69** [ZeTopHat/suse-vagrant-labs#64]
An error occurred while executing multiple actions in parallel.
Any errors that occurred are shown below.

An unexpected error occurred when executing the action on the
'basic12sp4' machine. Please report this as a bug:

undefined method `coerce' for an instance of String

/usr/share/vagrant/gems/gems/vagrant-libvirt-0.11.2/lib/vagrant-libvirt/util/byte_number.rb:35:in `coerce'
/usr/share/vagrant/gems/gems/vagrant-libvirt-0.11.2/lib/vagrant-libvirt/util/byte_number.rb:39:in `<=>'
/usr/share/vagrant/gems/gems/vagrant-libvirt-0.11.2/lib/vagrant-libvirt/util/byte_number.rb:39:in `<=>'
/usr/share/vagrant/gems/gems/vagrant-libvirt-0.11.2/lib/vagrant-libvirt/action/handle_box_image.rb:95:in `<'
/usr/share/vagrant/gems/gems/vagrant-libvirt-0.11.2/lib/vagrant-libvirt/action/handle_box_image.rb:95:in `call'
/usr/share/vagrant/gems/gems/vagrant-2.3.7/lib/vagrant/action/warden.rb:48:in `call'
/usr/share/vagrant/gems/gems/vagrant-2.3.7/lib/vagrant/action/builtin/handle_box.rb:56:in `call'
/usr/share/vagrant/gems/gems/vagrant-2.3.7/lib/vagrant/action/warden.rb:48:in `call'
/usr/share/vagrant/gems/gems/vagrant-libvirt-0.11.2/lib/vagrant-libvirt/action/handle_storage_pool.rb:63:in `call'
/usr/share/vagrant/gems/gems/vagrant-2.3.7/lib/vagrant/action/warden.rb:48:in `call'
/usr/share/vagrant/gems/gems/vagrant-libvirt-0.11.2/lib/vagrant-libvirt/action/set_name_of_domain.rb:34:in `call'
/usr/share/vagrant/gems/gems/vagrant-2.3.7/lib/vagrant/action/warden.rb:48:in `call'
/home/rmontes/.vagrant.d/gems/3.3.0/gems/vagrant-hostmanager-1.8.10/lib/vagrant-hostmanager/action/update_all.rb:24:in `call'
/usr/share/vagrant/gems/gems/vagrant-2.3.7/lib/vagrant/action/warden.rb:48:in `call'
/usr/share/vagrant/gems/gems/vagrant-2.3.7/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
/usr/share/vagrant/gems/gems/vagrant-2.3.7/lib/vagrant/action/warden.rb:48:in `call'
/usr/share/vagrant/gems/gems/vagrant-2.3.7/lib/vagrant/action/builtin/provision.rb:80:in `call'
/usr/share/vagrant/gems/gems/vagrant-2.3.7/lib/vagrant/action/warden.rb:48:in `call'
/usr/share/vagrant/gems/gems/vagrant-libvirt-0.11.2/lib/vagrant-libvirt/action/cleanup_on_failure.rb:21:in `call'
/usr/share/vagrant/gems/gems/vagrant-2.3.7/lib/vagrant/action/warden.rb:48:in `call'
/usr/share/vagrant/gems/gems/vagrant-2.3.7/lib/vagrant/action/warden.rb:127:in `block in finalize_action'
/usr/share/vagrant/gems/gems/vagrant-2.3.7/lib/vagrant/action/warden.rb:48:in `call'
/usr/share/vagrant/gems/gems/vagrant-2.3.7/lib/vagrant/action/builder.rb:180:in `call'
/usr/share/vagrant/gems/gems/vagrant-2.3.7/lib/vagrant/action/runner.rb:101:in `block in run'
/usr/share/vagrant/gems/gems/vagrant-2.3.7/lib/vagrant/util/busy.rb:19:in `busy'
/usr/share/vagrant/gems/gems/vagrant-2.3.7/lib/vagrant/action/runner.rb:101:in `run'
/usr/share/vagrant/gems/gems/vagrant-2.3.7/lib/vagrant/action/builtin/call.rb:53:in `call'
/usr/share/vagrant/gems/gems/vagrant-2.3.7/lib/vagrant/action/warden.rb:48:in `call'
/usr/share/vagrant/gems/gems/vagrant-2.3.7/lib/vagrant/action/builtin/box_check_outdated.rb:31:in `call'
/usr/share/vagrant/gems/gems/vagrant-2.3.7/lib/vagrant/action/warden.rb:48:in `call'
/usr/share/vagrant/gems/gems/vagrant-2.3.7/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
/usr/share/vagrant/gems/gems/vagrant-2.3.7/lib/vagrant/action/warden.rb:48:in `call'
/usr/share/vagrant/gems/gems/vagrant-2.3.7/lib/vagrant/action/builder.rb:180:in `call'
/usr/share/vagrant/gems/gems/vagrant-2.3.7/lib/vagrant/action/runner.rb:101:in `block in run'
/usr/share/vagrant/gems/gems/vagrant-2.3.7/lib/vagrant/util/busy.rb:19:in `busy'
/usr/share/vagrant/gems/gems/vagrant-2.3.7/lib/vagrant/action/runner.rb:101:in `run'
/usr/share/vagrant/gems/gems/vagrant-2.3.7/lib/vagrant/machine.rb:248:in `action_raw'
/usr/share/vagrant/gems/gems/vagrant-2.3.7/lib/vagrant/machine.rb:217:in `block in action'
/usr/share/vagrant/gems/gems/vagrant-2.3.7/lib/vagrant/environment.rb:631:in `lock'
/usr/share/vagrant/gems/gems/vagrant-2.3.7/lib/vagrant/machine.rb:203:in `call'
/usr/share/vagrant/gems/gems/vagrant-2.3.7/lib/vagrant/machine.rb:203:in `action'
/usr/share/vagrant/gems/gems/vagrant-2.3.7/lib/vagrant/batch_action.rb:86:in `block (2 levels) in run'

**Comment by ZeTopHat** [comment]
I believe you've run into a known issue with the SLE 12 SP4 vagrant box image provided by SUSE. That image specifically had this issue and as far as I know it was never fixed. However, you can fix it manually by doing the following:

1. Determine the box version for SLE 12 SP4 being used on your system with this command: `vagrant box list`
2. Open this file: `~/.vagrant.d/boxes/SLES-12-SP4-Vagrant.x86_64/<version>/libvirt/metadata.json`
3. Change from:

"virtual_size": "42"

to:

"virtual_size": 42

Then test to see if the issue has resolved.

**Comment by ZeTopHat** [comment]
Pull #76 resolved this issue since we control the box files now.
